// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcmsDQIu5NUaSF2g3UYm_yu5HGxnJl9LU',
    appId: '1:1057781533782:web:ecf164d7239a98f58a7ff7',
    messagingSenderId: '1057781533782',
    projectId: 'instagram-clone-6f802',
    authDomain: 'instagram-clone-6f802.firebaseapp.com',
    storageBucket: 'instagram-clone-6f802.appspot.com',
    measurementId: 'G-73BYS62W85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jbAXSPMExjFzQ2_IcHujCN3vAH9dUQU',
    appId: '1:1057781533782:android:37e916bbf2b8d2918a7ff7',
    messagingSenderId: '1057781533782',
    projectId: 'instagram-clone-6f802',
    storageBucket: 'instagram-clone-6f802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGv5TziZcJpZVV3IoneikFYfLyS8Va7Dk',
    appId: '1:1057781533782:ios:5933350f451d3d338a7ff7',
    messagingSenderId: '1057781533782',
    projectId: 'instagram-clone-6f802',
    storageBucket: 'instagram-clone-6f802.appspot.com',
    iosClientId:
        '1057781533782-s12hnaetbkco1182oekc01n7u6qsd9da.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
